name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Slack Worker
        run: |
          cd slack-worker
          wrangler deploy --env production --minify

      - name: Deploy Frame.io Worker
        run: |
          cd ../frameio-worker
          wrangler deploy --env production --minify

      - name: Deploy Airtable Worker
        run: |
          cd ../airtable-worker
          wrangler deploy --env production --minify
